language: scala

scala:
   - "2.11.0"

# specific configuration for continuous integration
script: sbt '; set javaOptions += "-Dconfig.file=conf/application.test-ci.conf" ; test'

after_script:
  - sbt '; set javaOptions += "-Dconfig.file=conf/application.test-ci.conf" ; coveralls'

services:
  - mongodb
  - redis-server

# works only for private repositories
cache:
  directories:
  - $HOME/.ivy2/cache

# deploy stable branch on heroku in staging
deploy:
  provider: heroku
  api_key:
    secure: DySHNynWdkOZqhTuLnse9syxaXoDtnL9fkbaN7nC+4tlIBrwtYXUIUNYiXVJeSnbC3pJte9GDsF0BD3cfmfqFG2w+RtdGVXnJXtsqUG3OlWkPlb87C9wqds4fyOnCeKPdu6DbCYjVxuAdWejGyKriGEGD0YJVx4dBgboh9rEcTc=
  app: yorrick-email-sender-staging
  on: stable
