language: scala

scala:
   - "2.10.4"

# specific configuration for continuous integration
script: sbt '; set javaOptions += "-Dconfig.file=conf/application.test-ci.conf" ; test'

after_script:
  - sbt '; set javaOptions += "-Dconfig.file=conf/application.test-ci.conf" ; coveralls'

services:
  - mongodb
  - redis-server

# works only for private repositories
cache:
  directories:
  - $HOME/.ivy2/cache

# deploy stable branch on heroku in staging
deploy:
  provider: heroku
  api_key: ZL5vozfDtimfeAG7Ku6kljtCRRp2VVoNMujiIh0hO9/gODTaHzRJzqwNm1pU6/fAsWnLqV/dEqQjmqHWVVpbjpGzouWTLIvtNEmRh1SgHxJtQKowmbT4RSpg43ggNyT0O5avWmH2UukwmSG1LV6rO2mF/jPT0Q7rlVvQjrUCtjo=
  on: stable
  app: yorrick-email-sender-staging
