language: scala

scala:
   - "2.10.4"

# specific configuration for continuous integration
script: sbt '; set javaOptions += "-Dconfig.file=conf/application.test-ci.conf" ; test'

after_script:
  - sbt '; set javaOptions += "-Dconfig.file=conf/application.test-ci.conf" ; coveralls'

services:
  - mongodb
  - redis-server

cache:
  directories:
  - $HOME/.ivy2/cache
